import { useState } from "react";

/* global Word */

export type DraftStatus = "idle" | "generating" | "success" | "error";

interface UseGenerateDraftReturn {
  generateDraft: (htmlContent: string) => Promise<void>;
  status: DraftStatus;
  error: string | null;
  reset: () => void;
}

export const useGenerateDraft = (): UseGenerateDraftReturn => {
  const [status, setStatus] = useState<DraftStatus>("idle");
  const [error, setError] = useState<string | null>(null);

  const generateDraft = async (htmlContent: string): Promise<void> => {
    if (!htmlContent) {
      setError("No content available to generate a draft.");
      setStatus("error");
      return;
    }

    setStatus("generating");
    setError(null);

    try {
      await Word.run(async (context) => {
        const body = context.document.body;

        // Clear the existing document content before inserting
        body.clear();

        // Insert a title at the top
        const title = body.insertParagraph("RFP Compliance Report", Word.InsertLocation.start);
        title.styleBuiltIn = Word.BuiltInStyleName.heading1;

        // Insert a horizontal line separator after the title
        const separator = body.insertParagraph(
          "─────────────────────────────────────",
          Word.InsertLocation.end
        );
        separator.font.color = "#CBD5E1";
        separator.font.size = 8;

        // Insert the streamed HTML content into the document
        // Word.InsertLocation.end appends after the title
        body.insertHtml(htmlContent, Word.InsertLocation.end);

        // Insert a footer paragraph
        const footer = body.insertParagraph(
          `Generated by RFP Compliance Checker — ${new Date().toLocaleDateString("en-GB", {
            day: "numeric",
            month: "long",
            year: "numeric",
          })}`,
          Word.InsertLocation.end
        );
        footer.font.size = 9;
        footer.font.color = "#94A3B8";
        footer.font.italic = true;

        await context.sync();
      });

      setStatus("success");
    } catch (err) {
      const message =
        err instanceof Error
          ? err.message
          : "Failed to generate the draft document. Please try again.";
      setError(message);
      setStatus("error");
    }
  };

  const reset = () => {
    setStatus("idle");
    setError(null);
  };

  return { generateDraft, status, error, reset };
};
